name: Ultra Fast Deploy (Rsync)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Build and Deploy
      run: |
        # Build JAR
        mvn clean package -DskipTests
        
        # Setup SSH
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
        # Ultra fast rsync transfer (only changed files)
        rsync -avz --delete \
          --exclude 'target/' \
          --exclude '.git/' \
          --exclude 'uploads/' \
          ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/diangraha/
        
        # Deploy on server
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /var/diangraha
          
          # Stop app
          pkill -f "diangraha-backend" || true
          
          # Setup MySQL once
          if ! docker ps | grep -q mysql; then
            docker run -d --name mysql \
              -e MYSQL_ROOT_PASSWORD=jhonreimon123 \
              -e MYSQL_DATABASE=diangraha_dev \
              -p 3306:3306 \
              mysql:8.0
            sleep 20
            docker exec mysql mysql -uroot -pjhonreimon123 -e "$(cat db-schema-diangraha.sql)"
          fi
          
          # Start app
          mkdir -p uploads
          nohup java -jar target/diangraha-backend-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          
          echo "Deployment completed!"
        EOF