name: Fast Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/diangraha
          
          # Stop existing containers
          docker compose down || true
          
          # Clone/pull latest code
          if [ -d "diangraha-backend" ]; then
            cd diangraha-backend
            git pull origin main
          else
            git clone https://github.com/jhonreimons/diangraha-backend.git
            cd diangraha-backend
          fi
          
          # Build and deploy
          docker compose build --no-cache
          docker compose up -d
          
          # Cleanup
          docker image prune -f